#!/bin/sh

# Modified By alban.lopez@gmail.com
# Script Path : /etc/init.d/firstrun
# Version : 0.41

### BEGIN INIT INFO
# Provides:          firstrun
# Required-Start:    $all
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to run when first starting
# Description:       Something needs to be done when  is
#                    starting at first time.
#                    regenerate ssh host key
### END INIT INFO

N=/etc/init.d/firstrun
MEMTOTAL=$(awk 'BEGIN { printf "%.0f\n", '$(grep MemTotal /proc/meminfo | awk '{print $2}')'/1024/1024 }')

MSG_FAIL="[ $(tput setaf 1)FAIL$(tput sgr 0) ]"
MSG_OK="[  $(tput setaf 2)OK$(tput sgr 0)  ]"
MSG_SKIP="[ $(tput setaf 3)SKIP$(tput sgr 0) ]"

set -e

do_expand_rootfs(){
        device="/dev/mmcblk0"
        ((echo d; echo n; echo p; echo 1; echo ; echo; echo w;) | fdisk $device)>/dev/null
return 0
}

case "$1" in
  start)
        reboot=false
        echo ""
        toilet -f standard "first run : OPT-Box"
        # if we have 1G ram reduce RAMLOG size
        if [ "$MEMTOTAL" = 1 ]; then
                sed -e 's/TMPFS_RAMFS_SIZE=512m/TMPFS_RAMFS_SIZE=256m/g' -i /etc/default/ramlog
                # for cubieboard disable some services
                if [ -f "/boot/cubieboard2.bin" ]; then
                        /sbin/insserv -r brcm40183-patch
                        /sbin/insserv -r disable_led.sh
                fi
        fi
        #
        echo "This process takes around one minute to finish..."
        #NEWMAC=00:01:43:`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`
        #sed -e 's/ether/ether '$NEWMAC'/g' -i /etc/network/interfaces.default
        #sed -e 's/ether/ether '$NEWMAC'/g' -i /etc/network/interfaces.hostapd
        # Cubietruck exception
                # if HDMI is attached during boot, set default screen output to HDMI
        if [ -n "$(dmesg | grep ParseEDID)" ] && [ -f "/boot/cubietruck.bin" ]; then
                bin2fex /boot/cubietruck.bin /tmp/tmp.fex
                sed -e 's/screen0_output_type.*/screen0_output_type     = 3/g' -i /tmp/tmp.fex
                fex2bin /tmp/tmp.fex /boot/cubietruck.bin
                echo "$MSG_OK Display enable"
        fi
        rm -f /etc/ssh/ssh_host*
        dpkg-reconfigure openssh-server 
        echo "$MSG_OK Reconfigure openSSH"
        set +e


        if [ "$(fping www.google.fr | grep alive)" != "" ]; then
                echo "$MSG_OK Updating packages list..."
                apt-get update >/dev/null 2>&1
                echo ""

        # Coaxis / alban personalize :
                echo "Install tools for Coaxis..."
                apt-get -y install htop iftop bmon >/dev/null 2>&1
        else
            echo "$MSG_SKIP Updating packages list."
        fi
        #
        echo "Expanding rootfs..."
        if do_expand_rootfs;then
                echo "$MSG_FAIL Expanding rootfs success, rebooting automatically." 
                /sbin/insserv resize2fs
                reboot=true
        else
                echo "$MSG_FAIL Expanding rootfs has failed, see log files." 
        fi

        /sbin/insserv -r firstrun

        # Coaxis / alban personalize :
	######################################################################################
        rm -f "/etc/udev/rules.d/70-persistent-net.rules"
        echo "root:C1i3ntRmSid3" | chpasswd

	if [ ! -d /home/coaxis ]; then
		echo "$MSG_OK Adding user : coaxis"
		adduser --quiet --disabled-password -shell /bin/bash --home /home/coaxis --gecos "Open Print Tunnel" coaxis
		addgroup coaxis sudo
		echo "coaxis:C1i3ntRmSid3" | chpasswd
	fi;
	######################################################################################

        if $reboot;then
            /sbin/reboot
        fi
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac


exit 0
